const productData = {
  "Móc khóa": [
    {
      title: "Móc khóa 1",
      image: "moc-khoa/moc_khoa_1",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 2",
      image: "moc-khoa/moc_khoa_2",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 3",
      image: "moc-khoa/moc_khoa_3",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 4",
      image: "moc-khoa/moc_khoa_4",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 5",
      image: "moc-khoa/moc_khoa_5",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 6",
      image: "moc-khoa/moc_khoa_6",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 7",
      image: "moc-khoa/moc_khoa_7",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
    {
      title: "Móc khóa 8",
      image: "moc-khoa/moc_khoa_8",
      extension: "JPG",
      description: "Mô tả Móc khóa …",
      price: "$999 ",
    },
  ],
  "Nam châm": [
    {
      title: "Nam châm 1",
      image: "nam-cham/nam_cham_1",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$999 ",
    },
    {
      title: "Nam châm 2",
      image: "nam-cham/nam_cham_2",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,000 ",
    },
    {
      title: "Nam châm 3",
      image: "nam-cham/nam_cham_3",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,001 ",
    },
    {
      title: "Nam châm 4",
      image: "nam-cham/nam_cham_4",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,002 ",
    },
    {
      title: "Nam châm 5",
      image: "nam-cham/nam_cham_5",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,003 ",
    },
    {
      title: "Nam châm 6",
      image: "nam-cham/nam_cham_6",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,004 ",
    },
    {
      title: "Nam châm 7",
      image: "nam-cham/nam_cham_7",
      extension: "jpeg",
      description: "Mô tả Nam châm …",
      price: "$1,005 ",
    },
  ],
  "Sổ gỗ": [
    {
      title: "Sổ gỗ 1",
      image: "so-go/so_go_1",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,005 ",
    },
    {
      title: "Sổ gỗ 2",
      image: "so-go/so_go_2",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,006 ",
    },
    {
      title: "Sổ gỗ 3",
      image: "so-go/so_go_3",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,007 ",
    },
    {
      title: "Sổ gỗ 4",
      image: "so-go/so_go_4",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,008 ",
    },
    {
      title: "Sổ gỗ 5",
      image: "so-go/so_go_5",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,009 ",
    },
    {
      title: "Sổ gỗ 6",
      image: "so-go/so_go_6",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,010 ",
    },
    {
      title: "Sổ gỗ 7",
      image: "so-go/so_go_7",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,011 ",
    },
    {
      title: "Sổ gỗ 8",
      image: "so-go/so_go_8",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,012 ",
    },
    {
      title: "Sổ gỗ 9",
      image: "so-go/so_go_9",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,013 ",
    },
    {
      title: "Sổ gỗ 10",
      image: "so-go/so_go_10",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,014 ",
    },
    {
      title: "Sổ gỗ 11",
      image: "so-go/so_go_11",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,015 ",
    },
    {
      title: "Sổ gỗ 12",
      image: "so-go/so_go_12",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,016 ",
    },
    {
      title: "Sổ gỗ 13",
      image: "so-go/so_go_13",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,017 ",
    },
    {
      title: "Sổ gỗ 14",
      image: "so-go/so_go_14",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,018 ",
    },
    {
      title: "Sổ gỗ 15",
      image: "so-go/so_go_15",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,019 ",
    },
    {
      title: "Sổ gỗ 16",
      image: "so-go/so_go_16",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,020 ",
    },
    {
      title: "Sổ gỗ 17",
      image: "so-go/so_go_17",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,021 ",
    },
    {
      title: "Sổ gỗ 18",
      image: "so-go/so_go_18",
      extension: "JPG",
      description: "Mô tả Sổ gỗ …",
      price: "$1,022 ",
    },
  ],
  "Thiệp giấy": [
    {
      title: "Thiệp giấy 1",
      image: "thiep-giay/thiep_giay_1",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,023 ",
    },
    {
      title: "Thiệp giấy 2",
      image: "thiep-giay/thiep_giay_2",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,024 ",
    },
    {
      title: "Thiệp giấy 3",
      image: "thiep-giay/thiep_giay_3",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,025 ",
    },
    {
      title: "Thiệp giấy 4",
      image: "thiep-giay/thiep_giay_4",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,026 ",
    },
    {
      title: "Thiệp giấy 5",
      image: "thiep-giay/thiep_giay_5",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,027 ",
    },
    {
      title: "Thiệp giấy 6",
      image: "thiep-giay/thiep_giay_6",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,028 ",
    },
    {
      title: "Thiệp giấy 7",
      image: "thiep-giay/thiep_giay_7",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,029 ",
    },
    {
      title: "Thiệp giấy 8",
      image: "thiep-giay/thiep_giay_8",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,030 ",
    },
    {
      title: "Thiệp giấy 9",
      image: "thiep-giay/thiep_giay_9",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,031 ",
    },
    {
      title: "Thiệp giấy 10",
      image: "thiep-giay/thiep_giay_10",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,032 ",
    },
    {
      title: "Thiệp giấy 11",
      image: "thiep-giay/thiep_giay_11",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,033 ",
    },
    {
      title: "Thiệp giấy 12",
      image: "thiep-giay/thiep_giay_12",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,034 ",
    },
    {
      title: "Thiệp giấy 13",
      image: "thiep-giay/thiep_giay_13",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,035 ",
    },
    {
      title: "Thiệp giấy 14",
      image: "thiep-giay/thiep_giay_14",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,036 ",
    },
    {
      title: "Thiệp giấy 15",
      image: "thiep-giay/thiep_giay_15",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,037 ",
    },
    {
      title: "Thiệp giấy 16",
      image: "thiep-giay/thiep_giay_16",
      extension: "JPG",
      description: "Mô tả Thiệp giấy …",
      price: "$1,038 ",
    },
  ],
  "Tranh màu": [
    {
      title: "Tranh màu 1",
      image: "tranh-mau/tranh_mau_1",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,038 ",
    },
    {
      title: "Tranh màu 2",
      image: "tranh-mau/tranh_mau_2",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,039 ",
    },
    {
      title: "Tranh màu 3",
      image: "tranh-mau/tranh_mau_3",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,040 ",
    },
    {
      title: "Tranh màu 4",
      image: "tranh-mau/tranh_mau_4",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,041 ",
    },
    {
      title: "Tranh màu 5",
      image: "tranh-mau/tranh_mau_5",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,042 ",
    },
    {
      title: "Tranh màu 6",
      image: "tranh-mau/tranh_mau_6",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,043 ",
    },
    {
      title: "Tranh màu 7",
      image: "tranh-mau/tranh_mau_7",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,044 ",
    },
    {
      title: "Tranh màu 8",
      image: "tranh-mau/tranh_mau_8",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,045 ",
    },
    {
      title: "Tranh màu 9",
      image: "tranh-mau/tranh_mau_9",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,046 ",
    },
    {
      title: "Tranh màu 10",
      image: "tranh-mau/tranh_mau_10",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,047 ",
    },
    {
      title: "Tranh màu 11",
      image: "tranh-mau/tranh_mau_11",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,048 ",
    },
    {
      title: "Tranh màu 12",
      image: "tranh-mau/tranh_mau_12",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,049 ",
    },
    {
      title: "Tranh màu 13",
      image: "tranh-mau/tranh_mau_13",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,050 ",
    },
    {
      title: "Tranh màu 14",
      image: "tranh-mau/tranh_mau_14",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,051 ",
    },
    {
      title: "Tranh màu 15",
      image: "tranh-mau/tranh_mau_15",
      extension: "JPG",
      description: "Mô tả Tranh màu …",
      price: "$1,052 ",
    },
  ],
  "Tranh gạo": [
    {
      title: "Tranh gạo 1",
      image: "tranh-gao/tranh_gao_1",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,052 ",
    },
    {
      title: "Tranh gạo 2",
      image: "tranh-gao/tranh_gao_2",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,053 ",
    },
    {
      title: "Tranh gạo 3",
      image: "tranh-gao/tranh_gao_3",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,054 ",
    },
    {
      title: "Tranh gạo 4",
      image: "tranh-gao/tranh_gao_4",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,055 ",
    },
    {
      title: "Tranh gạo 5",
      image: "tranh-gao/tranh_gao_5",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,056 ",
    },
    {
      title: "Tranh gạo 6",
      image: "tranh-gao/tranh_gao_6",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,057 ",
    },
    {
      title: "Tranh gạo 7",
      image: "tranh-gao/tranh_gao_7",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,058 ",
    },
    {
      title: "Tranh gạo 8",
      image: "tranh-gao/tranh_gao_8",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,059 ",
    },
  ],
  "Túi vải cotton": [
    {
      title: "Túi vải cotton 1",
      image: "tui-vai-cotton/tui_vai_cotton_1",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,059 ",
    },
    {
      title: "Túi vải cotton 2",
      image: "tui-vai-cotton/tui_vai_cotton_2",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,060 ",
    },
    {
      title: "Túi vải cotton 3",
      image: "tui-vai-cotton/tui_vai_cotton_3",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,061 ",
    },
    {
      title: "Túi vải cotton 4",
      image: "tui-vai-cotton/tui_vai_cotton_4",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,062 ",
    },
    {
      title: "Túi vải cotton 5",
      image: "tui-vai-cotton/tui_vai_cotton_5",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,063 ",
    },
    {
      title: "Túi vải cotton 6",
      image: "tui-vai-cotton/tui_vai_cotton_6",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,064 ",
    },
    {
      title: "Túi vải cotton 7",
      image: "tui-vai-cotton/tui_vai_cotton_7",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,065 ",
    },
    {
      title: "Túi vải cotton 8",
      image: "tui-vai-cotton/tui_vai_cotton_8",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,066 ",
    },
    {
      title: "Túi vải cotton 9",
      image: "tui-vai-cotton/tui_vai_cotton_9",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,067 ",
    },
    {
      title: "Túi vải cotton 10",
      image: "tui-vai-cotton/tui_vai_cotton_10",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,068 ",
    },
    {
      title: "Túi vải cotton 11",
      image: "tui-vai-cotton/tui_vai_cotton_11",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,069 ",
    },
    {
      title: "Túi vải cotton 12",
      image: "tui-vai-cotton/tui_vai_cotton_12",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,070 ",
    },
  ],
  Tượng: [
    {
      title: "Tượng 1",
      image: "tuong/tuong_1",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,070 ",
    },
    {
      title: "Tượng 2",
      image: "tuong/tuong_2",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,070 ",
    },
    {
      title: "Tượng 3",
      image: "tuong/tuong_3",
      extension: "JPG",
      description: "Mô tả Tranh gạo …",
      price: "$1,070 ",
    },
  ],
};

export default productData;
